import { Restaurant } from './siteContent';

export const neighborhoodRestaurants: Record<string, Restaurant[]> = {
  Shibuya: [
    {
      name: "Uobei Shibuya",
      neighborhood: "Shibuya",
      cuisine: "Sushi",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=1600&q=80",
      tags: ["Conveyor belt", "Quick service"],
      description: "High-tech conveyor belt sushi with touch-panel ordering and fresh selections.",
      rating: 4.3,
      distance: "0.3 km",
      phone: "+81-3-3780-0001",
    },
    {
      name: "Ichiran Shibuya",
      neighborhood: "Shibuya",
      cuisine: "Ramen",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1600&q=80",
      tags: ["Tonkotsu", "Solo dining"],
      description: "Famous tonkotsu ramen chain with individual booth seating for focused dining.",
      rating: 4.5,
      distance: "0.5 km",
      phone: "+81-3-3463-3667",
    },
    {
      name: "Gyukatsu Motomura",
      neighborhood: "Shibuya",
      cuisine: "Japanese",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1588347818036-8e4e4b0b1ac9?auto=format&fit=crop&w=1600&q=80",
      tags: ["Beef cutlet", "Popular"],
      description: "Tender beef cutlet served rare with a personal grill to cook to preference.",
      rating: 4.6,
      distance: "0.7 km",
      phone: "+81-3-6427-0806",
    },
    {
      name: "Narukiyo Izakaya",
      neighborhood: "Shibuya",
      cuisine: "Izakaya",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1600&q=80",
      tags: ["Local vibe", "Sake selection"],
      description: "Authentic izakaya atmosphere with extensive sake menu and seasonal dishes.",
      rating: 4.4,
      distance: "0.9 km",
      phone: "+81-3-5456-0789",
    },
    {
      name: "Sakuratei",
      neighborhood: "Shibuya",
      cuisine: "Okonomiyaki",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?auto=format&fit=crop&w=1600&q=80",
      tags: ["DIY cooking", "English menu"],
      description: "Cook your own okonomiyaki and monjayaki at your table in a fun atmosphere.",
      rating: 4.5,
      distance: "1.1 km",
      phone: "+81-3-3462-7667",
    },
  ],
  Shinjuku: [
    {
      name: "Kozue",
      neighborhood: "Shinjuku",
      cuisine: "Japanese",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=1600&q=80",
      tags: ["Park Hyatt", "Tokyo views"],
      description: "Contemporary Japanese cuisine 40 floors up with skyline views.",
      rating: 4.7,
      distance: "2.9 km",
      phone: "+81-3-5322-1234",
    },
    {
      name: "Omoide Yokocho Yakitori",
      neighborhood: "Shinjuku",
      cuisine: "Yakitori",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&w=1600&q=80",
      tags: ["Nostalgic", "Street food"],
      description: "Tiny yakitori stalls in historic alleyway with authentic Showa-era atmosphere.",
      rating: 4.5,
      distance: "0.2 km",
      phone: "+81-3-3342-5678",
    },
    {
      name: "Tsunahachi",
      neighborhood: "Shinjuku",
      cuisine: "Tempura",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1542528180-1c2803fa042b?auto=format&fit=crop&w=1600&q=80",
      tags: ["Since 1924", "Traditional"],
      description: "Historic tempura restaurant serving premium seafood and vegetable tempura sets.",
      rating: 4.6,
      distance: "0.4 km",
      phone: "+81-3-3352-1012",
    },
    {
      name: "Nagi Ramen Golden Gai",
      neighborhood: "Shinjuku",
      cuisine: "Ramen",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=1600&q=80",
      tags: ["Niboshi", "Late night"],
      description: "Unique niboshi (sardine) broth ramen in the famous Golden Gai district.",
      rating: 4.4,
      distance: "0.6 km",
      phone: "+81-3-3205-1925",
    },
    {
      name: "Imahan Shabu-shabu",
      neighborhood: "Shinjuku",
      cuisine: "Shabu-shabu",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1592415499556-e275ca1ea9de?auto=format&fit=crop&w=1600&q=80",
      tags: ["Wagyu", "Traditional"],
      description: "Premium wagyu shabu-shabu and sukiyaki since 1895.",
      rating: 4.7,
      distance: "0.8 km",
      phone: "+81-3-3352-1121",
    },
  ],
  Ginza: [
    {
      name: "Tempura Kondo",
      neighborhood: "Ginza",
      cuisine: "Tempura",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1542528180-1c2803fa042b?auto=format&fit=crop&w=1600&q=80",
      tags: ["Michelin ★★", "Seasonal"],
      description: "Legendary sweet potato tempura and impeccable technique.",
      rating: 4.7,
      distance: "1.8 km",
      phone: "+81-3-5568-0923",
    },
    {
      name: "Kyubey Ginza",
      neighborhood: "Ginza",
      cuisine: "Sushi",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1583623025817-d180a2221d0a?auto=format&fit=crop&w=1600&q=80",
      tags: ["Edomae", "Historic"],
      description: "Prestigious Edomae sushi establishment serving traditional nigiri since 1935.",
      rating: 4.8,
      distance: "0.3 km",
      phone: "+81-3-3571-6523",
    },
    {
      name: "Bird Land",
      neighborhood: "Ginza",
      cuisine: "Yakitori",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1625937329935-d0fb0a6d4e08?auto=format&fit=crop&w=1600&q=80",
      tags: ["Michelin ★", "Premium chicken"],
      description: "Refined yakitori using whole chickens, every part expertly prepared.",
      rating: 4.6,
      distance: "0.5 km",
      phone: "+81-3-5250-1081",
    },
    {
      name: "Ginza Kojyu",
      neighborhood: "Ginza",
      cuisine: "Kaiseki",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?auto=format&fit=crop&w=1600&q=80",
      tags: ["Michelin ★★", "Seasonal"],
      description: "Refined kaiseki showcasing seasonal ingredients with modern presentations.",
      rating: 4.9,
      distance: "0.7 km",
      phone: "+81-3-3572-6690",
    },
    {
      name: "Ginza Sushi Ichi",
      neighborhood: "Ginza",
      cuisine: "Sushi",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=1600&q=80",
      tags: ["Counter seating", "Fresh fish"],
      description: "High-quality sushi in intimate counter setting with daily market selections.",
      rating: 4.5,
      distance: "0.9 km",
      phone: "+81-3-3567-4555",
    },
  ],
  Roppongi: [
    {
      name: "Sushi Saito",
      neighborhood: "Roppongi",
      cuisine: "Sushi",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?auto=format&fit=crop&w=1600&q=80",
      tags: ["Omakase", "Michelin ★★★"],
      description: "Intimate 7-seat counter with exceptional nigiri and seasonal kaiseki.",
      rating: 4.9,
      distance: "2.3 km",
      phone: "+81-3-3589-4412",
    },
    {
      name: "Sukiyabashi Jiro Roppongi",
      neighborhood: "Roppongi",
      cuisine: "Sushi",
      priceRange: "¥¥¥¥",
      image: "https://images.unsplash.com/photo-1583623025817-d180a2221d0a?auto=format&fit=crop&w=1600&q=80",
      tags: ["Omakase", "World-famous"],
      description: "Branch of the legendary sushi master's restaurant.",
      rating: 4.9,
      distance: "2.4 km",
      phone: "+81-3-5413-6626",
    },
    {
      name: "Gonpachi Nishi-Azabu",
      neighborhood: "Roppongi",
      cuisine: "Izakaya",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1600&q=80",
      tags: ["Kill Bill restaurant", "Traditional"],
      description: "Famous izakaya with dramatic architecture, featured in Kill Bill film.",
      rating: 4.3,
      distance: "1.2 km",
      phone: "+81-3-5771-0170",
    },
    {
      name: "Tofuya Ukai",
      neighborhood: "Roppongi",
      cuisine: "Tofu Kaiseki",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?auto=format&fit=crop&w=1600&q=80",
      tags: ["Garden setting", "Traditional"],
      description: "Elegant tofu kaiseki in beautiful Japanese garden near Tokyo Tower.",
      rating: 4.6,
      distance: "1.8 km",
      phone: "+81-3-3436-1028",
    },
    {
      name: "Inakaya Roppongi",
      neighborhood: "Roppongi",
      cuisine: "Robatayaki",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1592415499556-e275ca1ea9de?auto=format&fit=crop&w=1600&q=80",
      tags: ["Theatrical", "Grilled dishes"],
      description: "Traditional robatayaki with theatrical presentation and premium ingredients.",
      rating: 4.5,
      distance: "0.4 km",
      phone: "+81-3-3408-5040",
    },
  ],
  Asakusa: [
    {
      name: "Daikokuya Tempura",
      neighborhood: "Asakusa",
      cuisine: "Tempura",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1542528180-1c2803fa042b?auto=format&fit=crop&w=1600&q=80",
      tags: ["Since 1887", "Traditional"],
      description: "Historic tempura restaurant known for large shrimp tempura on rice bowls.",
      rating: 4.4,
      distance: "0.2 km",
      phone: "+81-3-3844-1111",
    },
    {
      name: "Asakusa Imahan",
      neighborhood: "Asakusa",
      cuisine: "Sukiyaki",
      priceRange: "¥¥¥",
      image: "https://images.unsplash.com/photo-1592415499556-e275ca1ea9de?auto=format&fit=crop&w=1600&q=80",
      tags: ["Since 1895", "Wagyu"],
      description: "Premium sukiyaki and shabu-shabu with top-grade wagyu beef.",
      rating: 4.7,
      distance: "0.3 km",
      phone: "+81-3-3841-1114",
    },
    {
      name: "Sometaro Okonomiyaki",
      neighborhood: "Asakusa",
      cuisine: "Okonomiyaki",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1626804475297-41608ea09aeb?auto=format&fit=crop&w=1600&q=80",
      tags: ["Traditional house", "DIY"],
      description: "Casual okonomiyaki in a traditional Japanese house with tatami seating.",
      rating: 4.3,
      distance: "0.4 km",
      phone: "+81-3-3844-9502",
    },
    {
      name: "Komagata Dozeu",
      neighborhood: "Asakusa",
      cuisine: "Traditional Japanese",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=1600&q=80",
      tags: ["Since 1801", "Loach fish"],
      description: "Historic restaurant specializing in dojou (loach) dishes since Edo period.",
      rating: 4.2,
      distance: "0.5 km",
      phone: "+81-3-3842-4001",
    },
    {
      name: "Asakusa Unana",
      neighborhood: "Asakusa",
      cuisine: "Unagi",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1600&q=80",
      tags: ["Grilled eel", "Traditional"],
      description: "Traditional unagi (grilled eel) restaurant with time-honored preparation.",
      rating: 4.5,
      distance: "0.6 km",
      phone: "+81-3-3844-1800",
    },
  ],
  Harajuku: [
    {
      name: "Afuri Harajuku",
      neighborhood: "Harajuku",
      cuisine: "Ramen",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=1600&q=80",
      tags: ["Yuzu shio", "Modern"],
      description: "Light and citrusy yuzu shio ramen in modern, minimalist space.",
      rating: 4.4,
      distance: "0.8 km",
      phone: "+81-3-6433-5884",
    },
    {
      name: "Maisen Tonkatsu",
      neighborhood: "Harajuku",
      cuisine: "Tonkatsu",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?auto=format&fit=crop&w=1600&q=80",
      tags: ["Premium pork", "Historic building"],
      description: "Famous tonkatsu in converted public bathhouse with garden seating.",
      rating: 4.6,
      distance: "0.3 km",
      phone: "+81-3-3470-0071",
    },
    {
      name: "Kawaii Monster Cafe",
      neighborhood: "Harajuku",
      cuisine: "Cafe",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1600&q=80",
      tags: ["Colorful", "Instagram-worthy"],
      description: "Vibrant pop-art themed cafe with colorful dishes and playful atmosphere.",
      rating: 4.0,
      distance: "0.2 km",
      phone: "+81-3-5413-5773",
    },
    {
      name: "Harajuku Gyoza Lou",
      neighborhood: "Harajuku",
      cuisine: "Gyoza",
      priceRange: "¥",
      image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=1600&q=80",
      tags: ["Pan-fried", "Quick bites"],
      description: "Simple gyoza specialist serving crispy pan-fried dumplings all day.",
      rating: 4.3,
      distance: "0.4 km",
      phone: "+81-3-3406-4743",
    },
    {
      name: "Eggs 'n Things",
      neighborhood: "Harajuku",
      cuisine: "Cafe",
      priceRange: "¥¥",
      image: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1600&q=80",
      tags: ["Pancakes", "Hawaiian"],
      description: "Hawaiian-style pancakes and breakfast dishes popular with young crowds.",
      rating: 4.2,
      distance: "0.5 km",
      phone: "+81-3-5775-5735",
    },
  ],
};
